class_name SpriteSheet
extends Resource
## A horizontal strip of equal-size pixel frames and the animations that play them.
## Generated by tools/art/build.py into content/art/*.tres; the PNG can be replaced by
## hand-made art as long as frame_size and the frame count still match.

@export var texture: Texture2D
## Size of one frame in source pixels.
@export var frame_size: Vector2i = Vector2i(16, 16)
## The source pixel that sits on the node's position (e.g. a note's head centre, an
## NPC's feet).
@export var origin: Vector2i = Vector2i(8, 8)
## Screen pixels per source pixel.
@export var pixel_scale: int = 3
## Animation name -> frame indices.
@export var animations: Dictionary = {}
## Animation name -> frames per second.
@export var fps: Dictionary = {}


func frame_count() -> int:
	if texture == null:
		return 0
	return texture.get_width() / frame_size.x


func has_animation(anim: StringName) -> bool:
	return animations.has(String(anim))


func frames_of(anim: StringName) -> Array:
	return animations.get(String(anim), [0])


func fps_of(anim: StringName) -> float:
	return float(fps.get(String(anim), 4.0))


func region(frame: int) -> Rect2:
	return Rect2(frame * frame_size.x, 0, frame_size.x, frame_size.y)
