class_name EnvironmentBackdrop
extends Node2D
## The pixel scenery behind a room: a sky fixed to the screen, then far and near layers
## that scroll slower than the world. Tinted toward violet while the Rest holds the room.
## Art: assets/env/<area>_{sky,far,near}.png, generated by tools/art/env.py.
## In a room it follows the room (setup); the title and the intro use setup_area, with
## the layers drifting on their own and the hush set by hand.

const TUNING: EnvironmentTuning = preload("res://content/tuning/environment_tuning.tres")
const AREAS := ["ledger", "percussion", "wind", "string", "podium", "grand"]
const ART_SIZE := Vector2(320, 180)

var room: Node
var area := "ledger"
var height := 720.0
## Sideways drift of the near layer with no camera (px/s); the far layer drifts slower.
var drift := 0.0
## How far the Rest has tinted the scenery (0 to 1) when there is no room to follow.
var hush := 0.0
var _sky_layer: CanvasLayer
var _sky: TextureRect
var _layers: Array[Parallax2D] = []


## The environment art for a pillar family ("ledger" for anything without its own).
static func area_for(family: String) -> String:
	return family if family in AREAS else "ledger"


static func texture(area_id: String, layer: String) -> Texture2D:
	return load("res://assets/env/%s_%s.png" % [area_id, layer])


func setup(r: Node) -> void:
	room = r
	area = area_for(r.family)
	height = r.height
	z_index = -20


func setup_area(area_id: String, drift_speed := 0.0) -> void:
	area = area_for(area_id)
	drift = drift_speed
	z_index = -20


func _ready() -> void:
	_sky_layer = CanvasLayer.new()
	_sky_layer.layer = -100
	add_child(_sky_layer)
	_sky = TextureRect.new()
	_sky.texture = texture(area, "sky")
	_sky.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	_sky.stretch_mode = TextureRect.STRETCH_SCALE
	_sky.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	_sky_layer.add_child(_sky)
	_add_layer("far", TUNING.far_scroll)
	_add_layer("near", TUNING.near_scroll)


func _add_layer(layer: String, scroll: float) -> void:
	var p := Parallax2D.new()
	var size := ART_SIZE * TUNING.layer_scale
	p.scroll_scale = Vector2(scroll, 1.0)
	p.repeat_size = Vector2(size.x, 0.0)
	p.repeat_times = 3
	p.autoscroll = Vector2(-drift * scroll / TUNING.near_scroll, 0.0)
	add_child(p)
	var s := Sprite2D.new()
	s.texture = texture(area, layer)
	s.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	s.centered = false
	s.scale = Vector2.ONE * TUNING.layer_scale
	# The art's bottom sits on the room's bottom; above it in a tall room is open sky.
	s.position = Vector2(0.0, height - size.y)
	p.add_child(s)
	_layers.append(p)


func _process(_delta: float) -> void:
	var h: float = room.hush_visual if room != null else hush
	var tint := Color.WHITE.lerp(TUNING.hush_tint, h)
	_sky.modulate = tint
	for p in _layers:
		p.modulate = tint
