"""The game's pixel palette. Ink on paper, a violet hush for the Rest, and one
colour per pillar (matching src/data/pal.gd)."""
from pixel import hexc

P = {
    "outline": hexc("120f14"),
    "ink": hexc("2b2531"),
    "ink_light": hexc("51485f"),
    "ink_mid": hexc("3a3342"),
    "paper": hexc("f3ecd9"),
    "paper_dark": hexc("e4dbc3"),
    "paper_shade": hexc("cfc4a8"),
    "eye": hexc("ffffff"),
    "eye_dark": hexc("1b181c"),
    "sparkle": hexc("ffffff"),
    "blush": hexc("f08aa0"),
    "blush_soft": hexc("f6b3c1"),
    "mouth": hexc("d86a82"),
    "brow": hexc("120f14"),
    "gold": hexc("d3992a"),
    "gold_light": hexc("f1c95a"),
    "red": hexc("be2d2f"),
    # The Rest (enemies)
    "hush": hexc("3d3354"),
    "hush_light": hexc("6c5d92"),
    "hush_dark": hexc("261f36"),
    "hush_eye": hexc("ff5c7a"),
    "hush_glow": hexc("ffd166"),
    # Pillars
    "percussion": hexc("cd6337"),
    "percussion_light": hexc("e8905f"),
    "percussion_dark": hexc("8e3f22"),
    "wind": hexc("429b95"),
    "wind_light": hexc("7cc8bf"),
    "wind_dark": hexc("2a6a66"),
    "string": hexc("6e56b3"),
    "string_light": hexc("9c86de"),
    "string_dark": hexc("4a3a80"),
    "margin": hexc("bf376e"),
    "podium": hexc("bf993b"),
    "wood": hexc("8a5a36"),
    "wood_light": hexc("b07a4c"),
    "wood_dark": hexc("5e3b22"),
    "metal": hexc("b9b3a6"),
    "metal_light": hexc("e4dfd2"),
    "stone": hexc("7a7280"),
    "stone_light": hexc("9e96a3"),
    "stone_dark": hexc("514b57"),
}
